### ISSUE TITLE
Join forces with the turf package?

### ISSUE THREAD

**Issue by giorgio79** [navibyte/geospatial#1]
https://pub.dev/packages/turf

**Comment by navibyte** [comment]
Thanks for interest! Sounds interesting proposal, and it really would make sense to coordinate work on geospatial Dart libraries.

Looked now at the Turf.dart at https://github.com/dartclub/turf_dart. On the roadmap you have quite extensive list of geospatial functions to be developed. Seems you have already had good progress and hope we some day have all those planned functions available for Dart developers.

The https://github.com/navibyte/geospatial is a mono repo, now containing four Dart packages, two of them “non-geospatial” and two geospatial. The focus has been on building format-independent geometry, metadata and feature classes supporting not only lat-lon geographic coordinates but also projected coordinates. Some code from earlier version was extracted to non-geospatial package (ie. “attributes”) on latest version 0.4.0. And another focus is building basic level of client-side support for geospatial APIs. Still working on to reach these goals… 

Looking at pub.dev there are a bunch of other geospatial libraries too, for viewing maps, geocoding, wrappers on google map services and so on. Not listing those here, but there exists also few other GeoJSON data parsers, at least:
https://github.com/synw/geojson
https://github.com/chuyentt/geojson_vi

And related to geospatial calculations and transformations at least following:
https://github.com/maRci002/proj4dart
https://github.com/moovida/dart_jts
https://github.com/a14n/dart-geo
https://github.com/thib92/dart_geo
https://github.com/wingkwong/geodesy
https://github.com/kb0/maps_toolkit

And many other excellent libraries for geospatial Dart. Maybe need to check these too to see what’s already available. Or has anybody compared them already?
