### ISSUE TITLE
Equality and hashcodes on Point and other Geometry classes

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#12]
Most immutable classes uses `EquatableMixin` from [equatable](https://pub.dev/packages/equatable) package that _helps to implement equality without needing to explicitly override == and hashCode_

However for example points has common interface Point and multiple implementing classes like (Point2, Point3 etc.). Need some consideration how `==` and `hashCode` should work on these classes. Same issue with other classes extending Geometry.

**Comment by navispatial** [comment]
Check [API docs](https://pub.dev/documentation/collection/latest/collection/collection-library.html) of the [collection](https://pub.dev/packages/collection) package for "*utility functions and classes in the style of dart:collection to make working with collections easier*".

**Comment by navispatial** [comment]
Implementations on `geobase` for `Position`, `GeoPosition`, `Box` and `GeoBox`, and on `geocore` for `Point`, see other issues: [Equality and hashcode for (Geo)Position and (Geo)Box classes #89](#89).

**Comment by navispatial** [comment]
Implemented in pre-release 0.8.0-a.10 of beta 0.8.0.
