### ISSUE TITLE
How to calculate midpoint given a list of points?

### ISSUE THREAD

**Issue by 0radek** [navibyte/geospatial#135]
These points are all pretty close (usually <10 miles). I'm wondering if these tools have a way to calculate the center point given a list of points.

**Comment by navispatial** [comment]
Currently no such method or function yet implemented. But very probably coming in some future version...

Some choices might be, without any deeper analysis..
1) calculate the minimum bounding box covering all points, then get the center point of box calculated
   * ie. [MultiPoint.bounds](https://pub.dev/documentation/geocore/latest/data/MultiPoint/bounds.html) in the *geocore* package
2) calculate average coordinate values (x / y or longitude / latitude) by simply looping all points
3) first calculate [convex hull](https://en.wikipedia.org/wiki/Convex_hull), then get the `centroid` point of it
   * something like JTS has for Java: [ConvexHull](http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/algorithm/ConvexHull.html) and `getCentroid` method in [Geometry](http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/Geometry.html)

**Comment by navispatial** [comment]
Centroid2D function implemented (#191) in geobase version 1.0.0 (#175). Closing this.
