### ISSUE TITLE
Basic error management and logging features

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#14]
Currently just throws an exception when calling async fetching functions to read data from an external data source.

Consider is this fine, or some other mechanism. Or specific exception clasess.

**Comment by navispatial** [comment]
Data sources and services on `geodata` specificy service specific exceptions that can be catched (if needed) in the standard way. So no special mechanism to be introduced for error management.

Logging is out of scope of `geodata` services - clients using them should log if necessary.

So closing this issue.
