### ISSUE TITLE
Coordinate transformations on core classes (and reading datasource)

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#15]
Currently no support at all.

Need some specification what's really needed or not.

There are good libraries for coordinate transformations, at least following, maybe others too.

[proj4dart](https://github.com/maRci002/proj4dart) by maRci002: 
_A Dart library to transform point coordinates from one coordinate system to another, including datum transformations_

**Comment by navibyte** [comment]
* Coordinate and geometry transformations
  * at least abstractions that can be extended outside this package
  * with few transformation implementations for most common use cases (maybe)

**Comment by navispatial** [comment]
Description from README.md of pre version `0.8.0-a.1` coming soon...

----

Geographical and cartesian points, geometry objects, features and feature
collections can be projected using coordinate transformations.

Currently this package provides a consistent abstraction. Classes used to 
represent objects mentioned above contain `project(TransformPoint transform)` method returning a projected object. The transform function is defined as:

```dart
/// A function to transform the [source] point to a transformed point.
typedef TransformPoint = T Function<T extends Point>(T source);
```

There are some basic geometry transformation provided by the package.

For example to translate points you can use:

```dart
/// Returns a function to translate points by delta values of each axis.
TransformPoint translatePoint<C extends num>({C? dx, C? dy, C? dz, C? dm});
```

Similarily `scalePoint`, `scalePointBy` and `rotatePoint2D` returns functions to
project points by scaling with axis-specific factors, scaling with a constant 
factor, or rotating in 2D.

It's quite simple to define a custom transform function too:

```dart
/// Translates X by 10.0 and Y by 20.0, other coordinates (Z and M) not changed.
T _sampleFixedTranslate<T extends Point>(T source) =>
    source.copyWith(x: source.x + 10.0, y: source.y + 20.0) as T;
```

Now this function can be used to project points and other geometries:

```dart
  // Create a point and project it with a custom translation that returns
  // `Point3m.xyzm(110.0, 220.0, 50.0, 1.25)` after projection.
  Point3m.xyzm(100.0, 200.0, 50.0, 1.25).project(_sampleFixedTranslate);

  // The same transform function can be used to project also geometry objects.
  LineString.parse('100.0 200.0, 400.0 500.0', Point2.geometry)
      .project(_sampleFixedTranslate);

  // This returns a line string that has same coordinate values as: 
  // LineString.parse('110.0 220.0, 410.0 520.0', Point2.geometry)
```

Please note that currently there is no support for geospatial transformations
between coordinate reference systems on this package. However a custom tranform 
function as described above could be wired to delegate tranformation to other
packages as necessary.

**Comment by navispatial** [comment]
[Draft abstraction on the pre-release 0.8.0-a.2 of the upcoming 0.8.0 release](https://github.com/navibyte/geospatial/blob/main/dart/geocore/CHANGELOG.md#080)

**Comment by navispatial** [comment]
Version 0.8.0-a.2 implementation described above, renamed the `project` method name to `transform` on next upcoming 0.8.0-a.3 version.

**Comment by navispatial** [comment]
Latest plans for `transofrm` and `project` (not convert) function definitions:

```dart
/// A function to transform the [source] point of [T] to a point of [T].
///
/// Target points of [T] are created using [source] as a point factory.
typedef TransformPoint = T Function<T extends Point>(T source);

/// A function to project the [source] point of [T] to a point of [R].
///
/// When [factory] is provided, then target points of [R] are created using that
/// as a point factory. Otherwise a projection function uses it's own factory.
///
/// Note that a function could implement for example a map projection from
/// geographical points to projected cartesian points, or an inverse
/// projection (or an "unprojection") from projected cartesian points to 
/// geographical points. Both are called here "project point" functions.
typedef ProjectPoint<T extends Point, R extends Point> = R Function(
  T source, [
  PointFactory<R>? factory,
]);
```

**Comment by navispatial** [comment]
Changes coming on `0.8.0-a.9`:

Replace `ProjectPoint` function typedef with new `Projection` mixin:

```dart
/// A mixin defining an interface for (geospatial) projections.
///
/// A class that implements this mixin may provide for example a map projection
/// from geographical points to projected cartesian points, or an inverse
/// projection (or an "unprojection") from projected cartesian points to
/// geographical points. Both are called simply "projections" here.
/// 
/// The mixin specifies only `projectPoint` function, but it can be extended in
/// future to project using other data structures than points also (like
/// `projectPointSeries` etc.). If extended, then the mixin provides a default
/// implementation for any new methods.
mixin Projection<R extends Point> {
  /// Projects the [source] point to a point of [R].
  ///
  /// When [to] is provided, then target points of [R] are created using that
  /// as a point factory. Otherwise a projection uses it's own factory.
  ///
  /// Throws FormatException if cannot project.
  R projectPoint(Point source, {PointFactory<R>? to});
}
```

All classes implementing `ProjectionAdater` (new definition below) must be refactored (at least `forward` and `inverse` methods):

```dart
mixin ProjectionAdapter<FromPoint extends Point, ToPoint extends Point> {
  /// The source coordinate reference system (or projection), ie. "EPSG:4326".
  String get fromCrs;

  /// The target coordinate reference system (or projection), ie. "EPSG:3857".
  String get toCrs;

  /// Returns a projection that projects from [fromCrs] to [toCrs].
  ///
  /// By default, result points of [R] are created using [factory]. This can be
  /// overridden by giving another factory when using a projection.
  Projection<R> forward<R extends ToPoint>(PointFactory<R> factory);

  /// Returns a projection that unprojects from [toCrs] to [fromCrs].
  ///
  /// By default, result points of [R] are created using [factory]. This can be
  /// overridden by giving another factory when using a projection.
  Projection<R> inverse<R extends FromPoint>(PointFactory<R> factory);
}
```

All references to `ProjectPoint` also changed to `Projection`.

**Comment by navispatial** [comment]
Implemented on the `geocore` package. 

Would be a separate issue to provide support for reading data sources on the `geodata` package.
