### ISSUE TITLE
Refactor fromJson / toJson methods on model classes

### ISSUE THREAD

**Issue by navispatial** [navibyte/geospatial#150]
Use "the standard model" on model classes:

Model classes that can be represented as JSON Objects
* `fromJson(Map<String, dynamic> data)` 
* `Map<String, dynamic> toJson()`

Model classes that can be represented as JSON Arrays (that are not nested)
* `fromJson(Iterable<dynamic>)` (this could be also `fromJson(List<dynamic>)`)
* `List<dynamic> toJson()`

Also refactor some current uses on model classes of "fromData" / "toData" to use the standard naming (unless there is specific extra arguments).

**Comment by navispatial** [comment]
Special case to the role presented above; for example the new `FeatureCollection` shall have a constructor from JSON Object data, but it's not simple 1 : 1 mapping from json model fields to class member. Decoding / format information (for example for `GeoJSON` model) can be given on this constructor.

```dart
  /// Decodes a feature collection from [data] conforming to [format].
  ///
  /// Data should be a JSON Object as decoded by the standard `json.decode()`.
  ///
  /// Feature items on a collection contain a geometry of [T].
  ///
  /// When [format] is not given, then [GeoJSON] is used as a default.
  ///
  /// Format or decoder implementation specific options can be set by [options].
  static FeatureCollection<Feature<T>> fromData<T extends Geometry>(
    Map<String, dynamic> data, {
    TextReaderFormat<FeatureContent> format = GeoJSON.feature,
    Map<String, dynamic>? options,
  })
```

So this is named `fromData`, not `fromJson` here.

**Comment by navispatial** [comment]
[Implemented in release published at 2022-08-21](https://github.com/navibyte/geospatial/releases/tag/v0.10.0)

**Comment by marianhlavac** [comment]
@navispatial Why were `toData`/`toJson` methods removed in the latest versions? I can't seem to find any way to convert Geometry objects to data, only `toText` is available in the latest version.
