### ISSUE TITLE
Add EWKT support

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#29]
*Plan updated 2024-04-16*

Implementation for v.1.1.0
* Support decoding also EWKT data (ignoring an optional srid).
* Utilities to decode a coordinate type and SRID from WKT text.
* A sample for decoding EWKT text data.

**Comment by navispatial** [comment]
Implemented in [geobase version 1.1.0](https://pub.dev/packages/geobase/versions/1.1.0), see [milestone](https://github.com/navibyte/geospatial/milestone/1).

See also the article [Decode and encode GeoJSON, WKT and WKB in Dart and Flutter apps](https://medium.com/@navibyte/decode-and-encode-geojson-wkt-and-wkb-in-dart-and-flutter-apps-ab2ef4ece2f1)
