### ISSUE TITLE
Other Dart-libraries for coordinate transformations and projections, geographic algorithms, geospatial analysis and geodesy

### ISSUE THREAD

**Issue by navispatial** [navibyte/geospatial#52]
## Coordinate transformations and projections

Code  | Library | Description
------ | ------- | -----------
[proj4dart](https://github.com/maRci002/proj4dart) by maRci002 | [![pub package](https://img.shields.io/pub/v/proj4dart.svg)](https://pub.dev/packages/proj4dart) | A Dart library to transform point coordinates from one coordinate system to another, including datum transformations (Dart version of [proj4js](https://github.com/proj4js/proj4js)).
[wkt-parser-dart](https://github.com/fegyi001/wkt-parser-dart) by fegyi001 | [![pub package](https://img.shields.io/pub/v/wkt_parser.svg)](https://pub.dev/packages/wkt_parser) | Wkt-parser is a Dart version of proj4js/wkt-parser. With wkt-parser you can parse a WKT projection string (OGC, ESRI) into json that proj4dart can consume.
[mgrs_dart](https://github.com/fegyi001/mgrs_dart) by fegyi001 |  [![pub package](https://img.shields.io/pub/v/mgrs_dart.svg)](https://pub.dev/packages/mgrs_dart) | Utility for converting between WGS84 lat/lng and MGRS coordinates (Dart version of proj4js/mgrs)

## Geographic algorithms and geospatial analysis

Code  | Library | Description
------ | ------- | -----------
[turf_dart](https://github.com/dartclub/turf_dart) by dartclub | [![pub package](https://img.shields.io/pub/v/turf.svg)](https://pub.dev/packages/turf) | A [turf.js](https://github.com/Turfjs/turf)-like geospatial analysis library working with GeoJSON.
[dart-geo](https://github.com/a14n/dart-geo) by a14n |  [![pub package](https://img.shields.io/pub/v/geo.svg)](https://pub.dev/packages/geo) | A set of utility functions for geographic computations.
[dart-geotools](https://github.com/bitflippers/dart-geotools) by bitflippers | [![pub package](https://img.shields.io/pub/v/geotools.svg)](https://pub.dev/packages/geotools) | A Dart library that provides tools for manipulating and working with geospatial data.
[dart_jts](https://github.com/moovida/dart_jts) by moovida  | [![pub package](https://img.shields.io/pub/v/dart_jts.svg)](https://pub.dev/packages/dart_jts) | An ongoing effort to port the [Java Topology Suite](https://github.com/locationtech/jts) to Dart.
[poly_bool_dart](https://github.com/mohammedX6/poly_bool_dart) by mohammedX6  | [![pub package](https://img.shields.io/pub/v/poly_bool_dart.svg)](https://pub.dev/packages/poly_bool_dart) | Boolean operations on polygons (union, intersection, difference, xor) (a port of [polybooljs](https://github.com/velipso/polybooljs)).

## Geodesy

Code  | Library | Description
------ | ------- | -----------
[geodesy](https://github.com/wingkwong/geodesy) by wingkwong | [![pub package](https://img.shields.io/pub/v/geodesy.svg)](https://pub.dev/packages/geodesy) | Geodesic and trigonometric calculations based on a spherical Earth model.

**Comment by mohammedX6** [comment]
I have ported a libary that capable of doing all polygon Boolean operations on polygons (union, intersection, difference, xor) ( [More info here](https://pub.dev/packages/poly_bool_dart)

**Comment by navispatial** [comment]
This is document (should be elsewhere), not an actual issue, so close.
