### ISSUE TITLE
Full client-side support for calling OGC API Features service according to Part 1 + 2

### ISSUE THREAD

**Issue by navibyte** [navibyte/geospatial#9]
OGC API Features client is implemented by `OGCAPIFeatures` class.

Support for the OGC API Features standard, parts 1 + 2, is not yet complete.

Complete support with some tests included.

About standard:
https://ogcapi.ogc.org/features/
https://github.com/opengeospatial/ogcapi-features

**Comment by navibyte** [comment]
Support enhanced on BETA-version 0.5.0. Still some specs to read...

**Comment by navispatial** [comment]
Checking conformance class was made easier by #169. 

For BETA-version 0.12.0 targeting client-side support as identified by standard conformance classes:

* To support:
  * Part 1 / Core: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core
  * Part 1 / GeoJSON: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson
  * Part 2 / CRS: http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs
* Not to support (yet, but still conformance classes discoverable):
  * Part 1 / HTML: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html
  * Part 1 / GML, Simple Features Profile, Level 0: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0
  * Part 1 / GML, Simple Features Profile, Level 2: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2
  * Part 1 / OpenAPI Specification 3.0: http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30

**Comment by navispatial** [comment]
Changes on classes:
* `Links*
  * property `List<Link> get items;`change to `List<Link> get all` to avoid name conflict with "rel" type "items"
  * add "rel" types "items", "conformance" and "data" defined by OGC API Features / Part 1

**Comment by navispatial** [comment]
Support for OGC API Features Part 1 + Part 2 should be quite well for accessing JSON metadata and GeoJSON geospatial feature collections (and also OpenAPI document accessible as a parsed JSON Object tree).

Implemented in pre-release 0.12.0-dev.0 of [geodata 0.12.0](https://github.com/navibyte/geospatial/issues/177).
